### -----------------------------------------
### VARIABLES
### -----------------------------------------
@baseUrl = http://localhost:3007
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjQsImVtYWlsIjoicG91cmxldGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTc3NzkzMjk4MSwiZXhwIjoxNzc3OTMzODgxLCJhdWQiOiJhY2Nlc3MifQ.l970YZrtGFdpySksOo_lhCbbFTLVTZ1dRVJOD1GCxb4



### -----------------------------------------
### 1) Récupérer toutes les alertes
### -----------------------------------------
GET {{baseUrl}}/alerts
Authorization: {{token}}
Content-Type: application/json



### -----------------------------------------
### 2) Récupérer une alerte par ID
### -----------------------------------------
GET {{baseUrl}}/alerts/2
Authorization: {{token}}
Content-Type: application/json



### -----------------------------------------
### 3) Marquer une alerte comme lue
### -----------------------------------------
PATCH {{baseUrl}}/alerts/2/read
Authorization: {{token}}
Content-Type: application/json



### -----------------------------------------
### 4) Marquer toutes les alertes comme lues
### -----------------------------------------
PATCH {{baseUrl}}/alerts/read-all
Authorization: {{token}}
Content-Type: application/json



### -----------------------------------------
### 5) Supprimer une alerte
### -----------------------------------------
DELETE {{baseUrl}}/alerts/2
Authorization: {{token}}
Content-Type: application/json



### -----------------------------------------
### 6) Créer une transaction → doit générer une alerte
### -----------------------------------------
POST {{baseUrl}}/transactions
Authorization: {{token}}
Content-Type: application/json

{
  "amount": 200,
  "id_category": 1,
  "id_budget": 1,
  "date": "2024-05-01",
  "description": "Test dépassement"
}



### -----------------------------------------
### 7) Vérifier que l’alerte a été générée
### -----------------------------------------
GET {{baseUrl}}/alerts
Authorization: {{token}}
Content-Type: application/json



### -----------------------------------------
### 8) Nouvelle transaction dans la même catégorie
### → ne doit PAS créer une nouvelle alerte
### -----------------------------------------
POST {{baseUrl}}/transactions
Authorization: {{token}}
Content-Type: application/json

{
  "amount": 20,
  "id_category": 1,
  "id_budget": 1,
  "date": "2024-05-02",
  "description": "Encore un test"
}



### -----------------------------------------
### 9) Vérifier qu’aucune nouvelle alerte n’a été créée
### -----------------------------------------
GET {{baseUrl}}/alerts
Authorization: {{token}}
Content-Type: application/json
