# Redirection automatique de HTTP vers HTTPS
server {
    listen 80;
    server_name lapince.pooya-dev.com;
    return 301 https://$host$request_uri;
}


server {
    listen 443 ssl;
    server_name lapince.pooya-dev.com;

    # # Chemin d'accès aux certificats créés par Certbot
    ssl_certificate /etc/letsencrypt/live/lapince.pooya-dev.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/lapince.pooya-dev.com/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;

     # Security headers
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-Frame-Options "DENY" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;
    add_header Content-Security-Policy "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' ; object-src 'none'; frame-ancestors 'none';" always;
    
    location / {
        try_files $uri /index.html;
    }

    
    location /api/ {
        proxy_pass http://lapince-api-1:3007/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}